on:
  push:
    branches:
      - staging
    paths:
      - 'Backend/**'  # Trigger if any file in the 'backend' directory changes

jobs:
  docker-start:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # This step is necessary to ensure the repo is checked out

    - name: Create PEM Key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/alan.pem
        chmod 600 ~/.ssh/alan.pem

        # Add the EC2 instance to known_hosts
        ssh-keyscan ec2-18-236-74-56.us-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Connect to EC2 and execute commands
      run: |
        ssh -vvv -o ConnectTimeout=30 -i "/home/runner/.ssh/alan.pem" ec2-user@ec2-18-236-74-56.us-west-2.compute.amazonaws.com <<'EOF'
        echo "Successfully connected to EC2!"
        # GO TO DIRECTORY CONTAINING GIT REPOSITORY
        cd /home/ec2-user/tst_dir/dockerized-scheduler
        # SHUT DOWN CONTAINERS
        sudo docker-compose down
        # GET LATEST REPOSITORY
        git pull
        # BUILD NEW CONTAINERS
        sudo docker-compose up -d --build
        exit
        EOF
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Remove Secrets
      run: |
        echo "Removing Secrets"
        rm -f ~/.ssh/alan.pem
